### ISSUE TITLE
v2.11.2 is missing from DockerHub

### ISSUE THREAD

**Issue by TheDevMinerTV** [traefik/traefik-library-image#57] opened 2024-04-11 19:54 UTC
Or is DockerHub just slow with building images.

We have an automated build pipeline that packages Traefik with our configuration using the latest stable tag that it can can fetch from the GitHub API, which is currently v2.11.2 but it's missing from DockerHub which makes our builds fail.

**Comment by mathieuruellan** [comment] 2024-04-11 19:58
I agree the time between the release and the image availability on docker hub is long.
For v2.11.1,  ~18hours between the tag and the image. I didn't find any gh-action pushing the image on docker hub, I've no idea how it is done.

**Comment by ldez** [comment] 2024-04-11 19:58
Hello,

The Official Docker image is built by Docker itself with a special process.

So you have to wait.

Duplicate of a lot of issues.

https://github.com/traefik/traefik/issues/10590#issuecomment-2048469281

**Closed** 2024-04-11 19:59 UTC
