### ISSUE TITLE
linux/amd64 image is missing for v1.7.31

### ISSUE THREAD

**Issue by omegarus** [traefik/traefik-library-image#16] opened 2021-10-05 15:30 UTC
Hello.
From what I see there is no linux/amd64 image for v1.7.31 in official docker hub repo.
```$ docker pull traefik:v1.7.31
v1.7.31: Pulling from library/traefik
no matching manifest for linux/amd64 in the manifest list entries
```
```
$ docker pull traefik:v1.7.31-alpine
v1.7.31-alpine: Pulling from library/traefik
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by ldez** [comment] 2021-10-05 16:37
Duplicate of https://github.com/traefik/traefik/issues/8490

**Closed by ldez** 2021-10-05 16:37 UTC
