### ISSUE TITLE
Error pulling traefik:v3.2.0

### ISSUE THREAD

**Issue by aifrog** [traefik/traefik-library-image#73] opened 2024-10-28 19:29 UTC
If I pull traefik:v3.2.0 I get

`3.2.0: Pulling from library/traefik
no matching manifest for linux/amd64 in the manifest list entries`

If I pull traefik:latest I get v3.1.6 instead of v3.2.0

How to get traefik:v3.2.0?

**Comment by ldez** [comment] 2024-10-28 20:06
Hello,

The Official Docker image is built by Docker itself with a special process (not standard the Docker Hub process).

So you have to wait.

The PR on the official image repository: https://github.com/docker-library/official-images/pull/17799
The Docker CI: https://doi-janky.infosiftr.net/job/multiarch/view/images/view/traefik/

Duplicate of a lot of issues.

**Comment by kevinpollet** [comment] 2024-10-29 14:38
Hello @aifrog,

As explained by @ldez, official Docker images are built by Docker itself, everything should be ok now.

I am closing this issue accordingly.

**Closed as completed by kevinpollet** 2024-10-29 14:38 UTC
Labels: kind/question
