### ISSUE TITLE
traefik docker move to latest (v2.8.2) stopped working

### ISSUE THREAD

**Issue by KillerKelvUK** [traefik/traefik-library-image#29] opened 2022-08-12 13:21 UTC
Watchtower pulled down the latest image which immedaitely ceased to work.  Manually regressing to v2.8.1 restored services.

Docker log output below for failing image running on a Synology DS1019+...

```
$ docker logs traefik
time="2022-08-12T13:12:57Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
time="2022-08-12T13:12:57Z" level=error msg="Error in Go routine: runtime error: slice bounds out of range [2:1]"
time="2022-08-12T13:12:57Z" level=error msg="Stack: goroutine 54 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine({0x36a75c0?, 0xc0000d3f38})\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:66 +0xa5\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:56 +0x36\npanic({0x36a75c0, 0xc0000d3f38})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/paerser/parser.filler.setSlice({{0xb?, {0x3989c0e?, 0x0?}}}, {0x2ff49c0?, 0xc0001a6a80?, 0x334f7e1?}, 0xc000810900)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:157 +0xaa5\ngithub.com/traefik/paerser/parser.filler.fill({{0xe0?, {0x3989c0e?, 0x3477c60?}}}, {0x2ff49c0?, 0xc0001a6a80?, 0x77?}, 0xc0003a0080?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:105 +0x477\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x80?, {0x3989c0e?, 0x2d8dfd4?}}}, {0x36cfce0?, 0xc0001a6a80?, 0xc0003a0158?}, 0x4a2e28?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0xa0?, {0x3989c0e?, 0x3306580?}}}, {0x36cfce0?, 0xc0001a6a80?, 0x349bc00?}, 0xc0003a0210?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.setPtr({{0xf8?, {0x3989c0e?, 0x39a1241?}}}, {0x32c93a0?, 0xc0001c14f8?, 0xc0003a0268?}, 0x4a2e28?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x40?, {0x3989c0e?, 0x3306580?}}}, {0x32c93a0?, 0xc0001c14f8?, 0xc0003a02c0?}, 0xc0003a0330?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x8?, {0x3989c0e?, 0xc0003a03b0?}}}, {0xc00071b640?, 0xc0001c14f0?, 0x322c920?}, 0xc0001bef00?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x80?, {0x3989c0e?, 0xc00041b5e0?}}}, {0xc00071b640?, 0xc0001c14f0?, 0x389cfa0?}, 0xc0003a0430?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setPtr({{0xe0?, {0x3989c0e?, 0x46b087?}}}, {0xc00071b680?, 0xc0001c14f0?, 0x1?}, 0xc0003a0488?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x98?, {0x3989c0e?, 0x1?}}}, {0xc00071b680?, 0xc0001c14f0?, 0x98?}, 0x3295fae?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setMap({{0x7?, {0x3989c0e?, 0x0?}}}, {0x3230820?, 0xc0005c7590?, 0x3295fb6?}, 0xc0008107e0)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:308 +0x3e5\ngithub.com/traefik/paerser/parser.filler.fill({{0x60?, {0x3989c0e?, 0x4?}}}, {0x3230820?, 0xc0005c7590?, 0x0?}, 0x0?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:103 +0x44f\ngithub.com/traefik/paerser/parser.filler.setStruct({{0xe0?, {0x3989c0e?, 0xc0005c3490?}}}, {0x367f560?, 0xc0005c7590?, 0x31ce40b?}, 0x4f?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0xa0?, {0x3989c0e?, 0x199?}}}, {0x367f560?, 0xc0005c7590?, 0xc0001c66e0?}, 0x31ce406?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x4?, {0x3989c0e?, 0x0?}}}, {0x32c8ba0?, 0xc0001c66e0?, 0x31ce40b?}, 0x4f?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x60?, {0x3989c0e?, 0x98?}}}, {0x32c8ba0?, 0xc0001c66e0?, 0xc0005c28a8?}, 0x398aac3?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x8?, {0x3989c0e?, 0x1?}}}, {0x35e3060?, 0xc0001c66e0?, 0xc0003a09f8?}, 0x1af1bb9?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0xa0?, {0x3989c0e?, 0x4?}}}, {0x35e3060?, 0xc0001c66e0?, 0xc0003a0a80?}, 0x1af1a26?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.Fill({{0xa0?, {0x3989c0e?, 0x32c87a0?}}}, {0x32c87a0?, 0xc0001c66e0?}, 0xc0004d5c20)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:58 +0x13d\ngithub.com/traefik/paerser/parser.Fill({0x32c87a0?, 0xc0001c66e0?}, 0x4?, {0xa0?, {0x3989c0e?, 0xc0004d5c20?}})\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:28 +0x59\ngithub.com/traefik/paerser/file.DecodeContent({0xc000837800, 0x158e}, {0xc00036246c, 0x5}, {0x32c87a0, 0xc0001c66e0})\n\tgithub.com/traefik/paerser@v0.1.6/file/file.go:83 +0x1d8\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).decodeConfiguration(0xc00018e8c0?, {0xc000362450, 0x21}, {0xc000837800, 0x158e})\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:522 +0x31d\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).CreateConfiguration(0xc0001bf230, {0x4458090, 0xc0005c6ea0}, {0xc000362450, 0x21}, 0x7f37e82a3400?, {0x3021fc0, 0x61ccfe0})\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:486 +0x746\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).loadFileConfig(0xc0000c35f8?, {0x4458090, 0xc0005c6ea0}, {0xc000362450, 0x21}, 0x98?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:160 +0xfb\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).loadFileConfigFromDirectory(0x4458020?, {0x4458090, 0xc0005c6ea0}, {0xc0005f5230, 0x15}, 0x0)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:333 +0xa7f\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).BuildConfiguration(0xc0001bf230)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:81 +0x11e\ngithub.com/traefik/traefik/v2/pkg/provider/file.(*Provider).Provide(0xc0001bf230, 0xc0001c66a0?, 0x443ca50?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/file/file.go:49 +0x2f\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.maybeThrottledProvide.func1(0xc0007d4ea0, 0xc0001bf230?)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:57 +0xcf\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.ProviderAggregator.launchProvider({{0x443d298, 0xc00026f280}, {0x443ca50, 0xc0001bf230}, {0xc00018e100, 0x3, 0x4}, 0x2540be400}, 0x0?, 0xc000491b30, ...)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:208 +0x339\ngithub.com/traefik/traefik/v2/pkg/provider/aggregator.ProviderAggregator.Provide({{0x443d298, 0xc00026f280}, {0x443ca50, 0xc0001bf230}, {0xc00018e100, 0x3, 0x4}, 0x2540be400}, 0xc0007d4ea0, 0xc000491b30)\n\tgithub.com/traefik/traefik/v2/pkg/provider/aggregator/aggregator.go:180 +0xb0\ngithub.com/traefik/traefik/v2/pkg/server.(*ConfigurationWatcher).startProviderAggregator.func1()\n\tgithub.com/traefik/traefik/v2/pkg/server/configurationwatcher.go:76 +0x48\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:59 +0x5b\ncreated by github.com/traefik/traefik/v2/pkg/safe.GoWithRecover\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:53 +0x72\n"
```

**Comment by ldez** [comment] 2022-08-12 13:49
duplicate of https://github.com/traefik/traefik/issues/9249 and #28

**Closed by ldez** 2022-08-12 13:49 UTC
