### ISSUE TITLE
Docker: Update to 2.8.2 crashes fileprovider

### ISSUE THREAD

**Issue by alexanderharm** [traefik/traefik-library-image#28] opened 2022-08-12 09:09 UTC
Last night I was bitten by the update from 2.8.1 to 2.8.2 that had Traefik crashing with the following error:

```
time="2022-08-12T10:52:20+02:00" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
time="2022-08-12T10:52:20+02:00" level=error msg="Error in Go routine: runtime error: slice bounds out of range [2:1]"
time="2022-08-12T10:52:20+02:00" level=error msg="Stack: goroutine 47 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/traefik/traefik/v2/pkg/safe.defaultRecoverGoroutine({0x36a75c0?, 0xc00049e438})\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:66 +0xa5\ngithub.com/traefik/traefik/v2/pkg/safe.GoWithRecover.func1.1()\n\tgithub.com/traefik/traefik/v2/pkg/safe/routine.go:56 +0x36\npanic({0x36a75c0, 0xc00049e438})\n\truntime/panic.go:884 +0x212\ngithub.com/traefik/paerser/parser.filler.setSlice({{0xb?, {0x3989c0e?, 0x0?}}}, {0x2ff49c0?, 0xc0007bff80?, 0x334f7e1?}, 0xc0008fce10)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:157 +0xaa5\ngithub.com/traefik/paerser/parser.filler.fill({{0xe0?, {0x3989c0e?, 0x447fe98?}}}, {0x2ff49c0?, 0xc0007bff80?, 0x58?}, 0xc000846080?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:105 +0x477\ngithub.com/traefik/paerser/parser.filler.setStruct({{0x80?, {0x3989c0e?, 0x2d8dfd4?}}}, {0x36cfce0?, 0xc0007bff80?, 0xc000846158?}, 0x4a2e28?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:135 +0x178\ngithub.com/traefik/paerser/parser.filler.fill({{0xa0?, {0x3989c0e?, 0x3306580?}}}, {0x36cfce0?, 0xc0007bff80?, 0x349bc00?}, 0xc000846210?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:99 +0x4b3\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x88?, {0x3989c0e?, 0x39a1241?}}}, {0x32c93a0?, 0xc000824588?, 0xc000846268?}, 0x4a2e28?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x80?, {0x3989c0e?, 0x3306580?}}}, {0x32c93a0?, 0xc000824588?, 0x447fe98?}, 0x3230820?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x50?, {0x3989c0e?, 0x411cc4?}}}, {0xc000450580?, 0xc000824580?, 0x7a0000c00055cd68?}, 0x3?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0xc0?, {0x3989c0e?, 0x491dd7?}}}, {0xc000450580?, 0xc000824580?, 0x349bc00?}, 0xc000846430?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setPtr({{0x68?, {0x3989c0e?, 0x46b087?}}}, {0xc0004505c0?, 0xc000824580?, 0x4b1f01?}, 0xc000846488?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:123 +0x24b\ngithub.com/traefik/paerser/parser.filler.fill({{0x98?, {0x3989c0e?, 0x1?}}}, {0xc0004505c0?, 0xc000824580?, 0x3?}, 0x3295fae?)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:101 +0x465\ngithub.com/traefik/paerser/parser.filler.setMap({{0x7?, {0x3989c0e?, 0x0?}}}, {0x3230820?, 0xc0008caab0?, 0x3295fb6?}, 0xc0008fccf0)\n\tgithub.com/traefik/paerser@v0.1.6/parser/element_fill.go:308 +0x3e5\ngithub.com/traefik/paerser/parser.filler.fill({{0x60?, {0x3989c0e?, 0x4?}}}, {0x3230820?, 0xc0008caab0?, 0x0?}, 0x0?)\n\tgithub.com/traefik/
```

**Comment by ldez** [comment] 2022-08-12 09:27
duplicate of https://github.com/traefik/traefik/issues/9249

**Closed by ldez** 2022-08-12 09:27 UTC
